/* This file is a part of the Eternar SDK. */

#if defined _ESDK_included_
  #endinput
#endif
#define _ESDK_included_

#include <sdktools>

#include "helpers.inc"

#include "methodmaps/CBaseEntity.inc"
#include "methodmaps/CBaseAnimating.inc"
#include "methodmaps/CBaseAttributableItem.inc"
#include "methodmaps/CBaseViewModel.inc"
#include "methodmaps/CBaseWeaponWorldModel.inc"

#include "methodmaps/CBaseCombatWeapon.inc"
#include "methodmaps/CBaseCombatCharacter.inc"

#include "methodmaps/CBasePlayer.inc"

#include "methodmaps/CGameRules.inc"

#include "methodmaps/misc/EternarMenu.inc"
#include "methodmaps/misc/PluginManager.inc"
#include "methodmaps/misc/StringTable.inc"
#include "methodmaps/misc/ConsoleVariable.inc"
#include "methodmaps/misc/DateTime.inc"
#include "methodmaps/misc/Server.inc"